name: 'Build and Test Solidity Contracts | The-Poolz'
description: 'Build and test Solidity contracts using Hardhat and Slither'
branding:
  icon: 'microscope'
  color: 'purple'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests, coverage, and Slither in parallel
      shell: bash
      run: |
        echo "Running tests, coverage, and Slither in parallel..."
        node scripts/test.js &
        node scripts/coverage.js &
        node scripts/slither.js &
        wait
