name: 'Build and Test Solidity Contracts | The-Poolz'
description: 'Build and test Solidity contracts using Hardhat and Slither'
branding:
  icon: 'microscope'
  color: 'purple'

runs:
  using: 'composite'
  steps:
    - name: Setup
      uses: ./workflows/setup.yml

    - name: Test
      uses: ./workflows/test.yml
      with:
        requires: [setup]

    - name: Coverage Test
      uses: ./workflows/coverage-test.yml
      with:
        requires: [setup]

    - name: Slither Test
      uses: ./workflows/slither-test.yml
      with:
        requires: [setup]
