name: 'Build and Test Solidity Contracts | The-Poolz'
description: 'Build and test Solidity contracts using Hardhat and Slither'

runs:
  using: 'composite'
  steps:
    - name: Setup
      uses: ./.github/workflows/setup.yml

    - name: Test
      uses: ./.github/workflows/test.yml
      with:
        requires: [Setup]

    - name: Coverage Test
      uses: ./.github/workflows/coverage-test.yml
      with:
        requires: [Setup]

    - name: Slither Test
      uses: ./.github/workflows/slither-test.yml
      with:
        requires: [Setup]
