name: "Build and Test Solidity Contracts | The-Poolz"
description: "Build and test Solidity contracts using Hardhat and Slither"

runs:
  using: "composite"
  steps:
    - name: setup
      uses: ./workflows/setup.yml