name: 'Build and Test Solidity Contracts | The-Poolz'
description: 'Build and test Solidity contracts using Hardhat and Slither'
branding:
  icon: 'microscope'
  color: 'purple'

on:
  workflow_call:

jobs:
  setup:
    uses: ./workflows/setup.yml

  test:
    needs: setup
    uses: ./workflows/test.yml

  coverage:
    needs: setup
    uses: ./workflows/coverage-test.yml

  audit:
    needs: setup
    uses: ./workflows/slither-test.yml
