name: 'Build and Test Solidity Contracts | The-Poolz'
description: 'Build and test Solidity contracts using Hardhat and Slither'
branding:
  icon: 'microscope'
  color: 'purple'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.9.0'

    - name: Cache node modules
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Run tests
      run: npx hardhat test

    - name: Run tests and generate coverage
      run: npx hardhat coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Run Slither
      uses: crytic/slither-action@v0.4.0
      id: slither
      with:
        node-version: '20.9.0'
        fail-on: high
        slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/

    - name: Create/update checklist as PR comment
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        REPORT: ${{ steps.slither.outputs.stdout }}
      with:
        script: |
          const header = '# Slither report'
          const body = process.env.REPORT
          const issue_number = context.payload.pull_request.number
          github.rest.issues.createComment({
            issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${header}\n\n${body}`
          })
