name: 'Build and Test Solidity Contracts | The-Poolz'
description: 'Build and test Solidity contracts using Hardhat and Slither'
branding:
  icon: 'microscope'
  color: 'purple'

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    needs: setup
    uses: ./.github/workflows/test.yml

  coverage:
    needs: setup
    uses: ./.github/workflows/coverage-test.yml

  audit:
    needs: setup
    uses: ./.github/workflows/slither-test.yml
