name: 'Build and Test Solidity Contracts | The-Poolz'

on:
  workflow_call:
    secrets:
      codecov_token:
        description: 'Codecov token'
        required: true
      bscscan_api_key:
          description: 'BSCSCAN token'
          required: false
      cmc_api_key:
          description: 'CMC token'
          required: false

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    needs: setup
    uses: ./.github/workflows/gas-test.yml
    secrets:
      bscscan_api_key: ${{ secrets.BSCSCAN_API_KEY }}
      cmc_api_key: ${{ secrets.CMC_API_KEY }}

  slither-test:
    needs: setup
    uses: ./.github/workflows/slither-test.yml

  coverage-test:
    needs: setup
    uses: ./.github/workflows/coverage-test.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
